/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_examples_jni_JNIExamples */

#ifndef _Included_com_ibm_examples_jni_JNIExamples
#define _Included_com_ibm_examples_jni_JNIExamples
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_examples_jni_JNIExamples
 * Method:    improveRNGSeed0
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_examples_jni_JNIExamples_improveRNGSeed0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
