// Generated by jextract

package com.ibm.examples.auto;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class FFMAuto extends FFMAuto$shared {

    FFMAuto() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup("build/lib/libjni-examples.dylib", LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());


    private static class hash_base$constants {
        public static final OfInt LAYOUT = FFMAuto.C_INT;
        public static final MemorySegment SEGMENT = SYMBOL_LOOKUP.findOrThrow("hash_base").reinterpret(LAYOUT.byteSize());
    }

    /**
     * Layout for variable:
     * {@snippet lang=c :
     * unsigned int hash_base
     * }
     */
    public static OfInt hash_base$layout() {
        return hash_base$constants.LAYOUT;
    }

    /**
     * Segment for variable:
     * {@snippet lang=c :
     * unsigned int hash_base
     * }
     */
    public static MemorySegment hash_base$segment() {
        return hash_base$constants.SEGMENT;
    }

    /**
     * Getter for variable:
     * {@snippet lang=c :
     * unsigned int hash_base
     * }
     */
    public static int hash_base() {
        return hash_base$constants.SEGMENT.get(hash_base$constants.LAYOUT, 0L);
    }

    /**
     * Setter for variable:
     * {@snippet lang=c :
     * unsigned int hash_base
     * }
     */
    public static void hash_base(int varValue) {
        hash_base$constants.SEGMENT.set(hash_base$constants.LAYOUT, 0L, varValue);
    }

    private static class hash_string {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFMAuto.C_INT,
            FFMAuto.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("hash_string");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * unsigned int hash_string(const char *str)
     * }
     */
    public static FunctionDescriptor hash_string$descriptor() {
        return hash_string.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * unsigned int hash_string(const char *str)
     * }
     */
    public static MethodHandle hash_string$handle() {
        return hash_string.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * unsigned int hash_string(const char *str)
     * }
     */
    public static MemorySegment hash_string$address() {
        return hash_string.ADDR;
    }

    /**
     * {@snippet lang=c :
     * unsigned int hash_string(const char *str)
     * }
     */
    public static int hash_string(MemorySegment str) {
        var mh$ = hash_string.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("hash_string", str);
            }
            return (int)mh$.invokeExact(str);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class callback_ffm {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFMAuto.C_INT,
            FFMAuto.C_POINTER,
            FFMAuto.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("callback_ffm");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int callback_ffm(const char *str, int (*printObj)(const void *))
     * }
     */
    public static FunctionDescriptor callback_ffm$descriptor() {
        return callback_ffm.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int callback_ffm(const char *str, int (*printObj)(const void *))
     * }
     */
    public static MethodHandle callback_ffm$handle() {
        return callback_ffm.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int callback_ffm(const char *str, int (*printObj)(const void *))
     * }
     */
    public static MemorySegment callback_ffm$address() {
        return callback_ffm.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int callback_ffm(const char *str, int (*printObj)(const void *))
     * }
     */
    public static int callback_ffm(MemorySegment str, MemorySegment printObj) {
        var mh$ = callback_ffm.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("callback_ffm", str, printObj);
            }
            return (int)mh$.invokeExact(str, printObj);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

